### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by SamuelMarks** [rouming/docopt.c#1]
I like the look of your project. Happy to contribute even… but what's the license?

Can I recommend zlib?

https://en.wikipedia.org/wiki/Zlib_License
https://opensource.org/licenses/Zlib

**Comment by rouming** [comment]
Hey. No objections. I'm happy to apply the license file if you send me the pull request. Thanks.

**Comment by SamuelMarks** [comment]
Great, thanks. My next contribution will focus on generator support.
